Expose a Session's control socket path
openssh-rust/openssh pull request #41
Opened 2022-02-24 15:18 UTC by stepga

In some situations, it's handy to have access to a SSH session's control
socket path. Therefore, expose it via a getter function.

2022-02-24 23:47 UTC, NobodyXu requested changes

2022-02-24 23:47 UTC, NobodyXu commented on src/lib.rs
> +    pub fn ctl_path(&self) -> Box<Path> {
I would like ctl_path to return &Path to avoid allocation if possible.

2022-02-24 23:48 UTC, NobodyXu commented
@stepga You would also need to change native_mux_impl/session.rs, adding this new function to it.

2022-02-25 11:57 UTC, NobodyXu commented
LGTM

2022-02-26 00:45 UTC, stepga commented
I'm sorry to have pushed yet another revision of such an easy patch, but the last revision did not compile :-/
The reason for my confusion was the different naming of both implementations' `Session` struct fields (`tempdir` & `ctl` vs `ctl` and `ctl_path`).

2022-02-26 00:52 UTC, NobodyXu commented
> I'm sorry to have pushed yet another revision of such an easy patch,

It is absolutely OK to push new revisions to fix mistakes at anytime.

> but the last revision did not compile :-/

I strongly recommend you to run script `run_ci_tests.sh` to test your implementation for bugs.

> The reason for my confusion was the different naming of both implementations' `Session` struct fields (`tempdir` & `ctl` vs `ctl` and `ctl_path`).

This change is a bit large, however I actually welcomed this change since it improves readability.

2022-02-26 00:53 UTC, NobodyXu requested changes

2022-02-26 00:53 UTC, NobodyXu commented on src/lib.rs
> +//! Scriptable SSH through OpenSSH (**only works on unix**)
I would like the `.` to be add back here.

2022-02-26 00:58 UTC, NobodyXu requested changes

2022-02-26 00:58 UTC, NobodyXu commented on src/process_impl/session.rs
> +        let _ctl = match self.tempdir.take() {
You can rename this variable to `_tempdir`.

2022-02-26 00:59 UTC, NobodyXu commented
@stepga I strongly recommend you to not do force push everytime, IMHO that makes review a bit difficult.

2022-02-26 01:12 UTC, stepga commented
> @stepga I strongly recommend you to not do force push everytime, IMHO that makes review a bit difficult.

thanks for the hints.
i'm only familiar with gerrit and lurked my whole life on github without actually committing to projects.

2022-02-26 01:16 UTC, NobodyXu commented
@stepga You are welcome!

2022-02-26 19:52 UTC, jonhoo requested changes
Thanks! Looks good to me with that small naming tweak :)

2022-02-26 19:52 UTC, jonhoo commented on src/lib.rs
> +    pub fn ctl(&self) -> &Path {
Let's give this a more friendly name, like `control_socket`.

2022-02-26 20:37 UTC, merged